// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Ockam
{
    [OckamResourceType("ockam:index/ockamIdentity:OckamIdentity")]
    public partial class OckamIdentity : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The JSON representation of the Ockam identity.
        /// </summary>
        [Output("identity")]
        public Output<string> Identity { get; private set; } = null!;

        /// <summary>
        /// The JSON representation of the Ockam vault.
        /// </summary>
        [Output("vault")]
        public Output<string> Vault { get; private set; } = null!;


        /// <summary>
        /// Create a OckamIdentity resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public OckamIdentity(string name, OckamIdentityArgs? args = null, CustomResourceOptions? options = null)
            : base("ockam:index/ockamIdentity:OckamIdentity", name, args ?? new OckamIdentityArgs(), MakeResourceOptions(options, ""))
        {
        }

        private OckamIdentity(string name, Input<string> id, OckamIdentityState? state = null, CustomResourceOptions? options = null)
            : base("ockam:index/ockamIdentity:OckamIdentity", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing OckamIdentity resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static OckamIdentity Get(string name, Input<string> id, OckamIdentityState? state = null, CustomResourceOptions? options = null)
        {
            return new OckamIdentity(name, id, state, options);
        }
    }

    public sealed class OckamIdentityArgs : global::Pulumi.ResourceArgs
    {
        public OckamIdentityArgs()
        {
        }
        public static new OckamIdentityArgs Empty => new OckamIdentityArgs();
    }

    public sealed class OckamIdentityState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The JSON representation of the Ockam identity.
        /// </summary>
        [Input("identity")]
        public Input<string>? Identity { get; set; }

        /// <summary>
        /// The JSON representation of the Ockam vault.
        /// </summary>
        [Input("vault")]
        public Input<string>? Vault { get; set; }

        public OckamIdentityState()
        {
        }
        public static new OckamIdentityState Empty => new OckamIdentityState();
    }
}
