# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .ockam_identity import *
from .provider import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "ockam",
  "mod": "index/ockamIdentity",
  "fqn": "pulumi_ockam",
  "classes": {
   "ockam:index/ockamIdentity:OckamIdentity": "OckamIdentity"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "ockam",
  "token": "pulumi:providers:ockam",
  "fqn": "pulumi_ockam",
  "class": "Provider"
 }
]
"""
)
