// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class OckamIdentity extends pulumi.CustomResource {
    /**
     * Get an existing OckamIdentity resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: OckamIdentityState, opts?: pulumi.CustomResourceOptions): OckamIdentity {
        return new OckamIdentity(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'ockam:index/ockamIdentity:OckamIdentity';

    /**
     * Returns true if the given object is an instance of OckamIdentity.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is OckamIdentity {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === OckamIdentity.__pulumiType;
    }

    /**
     * The JSON representation of the Ockam identity.
     */
    public /*out*/ readonly identity!: pulumi.Output<string>;
    /**
     * The JSON representation of the Ockam vault.
     */
    public /*out*/ readonly vault!: pulumi.Output<string>;

    /**
     * Create a OckamIdentity resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: OckamIdentityArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: OckamIdentityArgs | OckamIdentityState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as OckamIdentityState | undefined;
            resourceInputs["identity"] = state ? state.identity : undefined;
            resourceInputs["vault"] = state ? state.vault : undefined;
        } else {
            const args = argsOrState as OckamIdentityArgs | undefined;
            resourceInputs["identity"] = undefined /*out*/;
            resourceInputs["vault"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(OckamIdentity.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering OckamIdentity resources.
 */
export interface OckamIdentityState {
    /**
     * The JSON representation of the Ockam identity.
     */
    identity?: pulumi.Input<string>;
    /**
     * The JSON representation of the Ockam vault.
     */
    vault?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a OckamIdentity resource.
 */
export interface OckamIdentityArgs {
}
